# Generated by Django 2.1.3 on 2018-12-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemagenda',
            name='data',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
